---
- name: "Create hbase Path {{ opentsdb_install_dir }}"
  file:
    path: "{{ opentsdb_install_dir }}"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: "Create hbase log Path {{ opentsdb_log_dir }}"
  file:
    path: "{{ opentsdb_log_dir }}"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: "copy {{ opentsdb_install_tar }} to {{ opentsdb_install_dir }}"
  copy:
    src: "files/{{ opentsdb_install_tar }}"
    dest: "{{ opentsdb_install_dir }}"

- name: "Extract {{ opentsdb_install_tar }} into {{ opentsdb_install_dir }}"
  unarchive:
    remote_src: yes
    src: "{{ opentsdb_install_dir }}/{{ opentsdb_install_tar }}"
    dest: "{{ opentsdb_install_dir }}"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    extra_opts: [--strip-components=1]
