---
- name: "Create opentsdb Path {{ opentsdb_install_dir }}"
  file:
    path: "{{ opentsdb_install_dir }}"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: "Create opentsdb log Path {{ opentsdb_log_dir }}"
  file:
    path: "{{ opentsdb_log_dir }}"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: "Create opentsdb tmp Path {{ opentsdb_tmp_dir }}"
  file:
    path: "{{ opentsdb_tmp_dir }}"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: "Create opentsdb conf dir {{ opentsdb_log_dir }}"
  file:
    path: "{{ opentsdb_conf_dir }}"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: "copy {{ opentsdb_install_tar }} to {{ opentsdb_install_dir }}"
  copy:
    src: "files/{{ opentsdb_install_tar }}"
    dest: "{{ opentsdb_install_dir }}"

- name: "Extract {{ opentsdb_install_tar }} into {{ opentsdb_install_dir }}"
  unarchive:
    remote_src: yes
    src: "{{ opentsdb_install_dir }}/{{ opentsdb_install_tar }}"
    dest: "{{ opentsdb_install_dir }}"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    extra_opts: [--strip-components=1]

- name: "add OpenTSDB startup file tsdb"
  template:
    src: templates/tsdb.j2
    dest: "{{ opentsdb_install_dir }}/bin/tsdb"
    mode: "u=rwx,g=rx,o=rx"
  notify:
    - restart opentsdb

- name: "configure OpenTSDB"
  template:
    src: templates/opentsdb.conf.j2
    dest: "{{ opentsdb_conf_dir }}/opentsdb.conf"
  notify:
    - restart opentsdb

- name: "configure OpenTSDB logging"
  template:
    src: templates/logback.xml.j2
    dest: "{{ opentsdb_conf_dir }}/logback.xml"
  notify:
    - restart opentsdb

- name: "copy tsdb-metric.sh"
  template:
    src: "tsdb-metrics.sh.j2"
    dest: "{{ opentsdb_install_dir }}/bin/tsdb-metrics.sh"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    mode: "u=rwx,g=rwx,o=rwx"

- name: Copy OpenTSDB service file
  template:
    src: opentsdb.ini.j2
    dest: "{{ supervisord_ini_dir }}/opentsdb.ini"
    owner: "{{ opentsdb_user }}"
    group: "{{ opentsdb_group }}"
    mode: "u=rw,g=r,o=r"
  notify:
    - update supervisord
    - restart opentsdb
